// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oxzewqmwyfqwnsgprhne.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im94emV3cW13eWZxd25zZ3ByaG5lIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAwMDIxOTcsImV4cCI6MjA2NTU3ODE5N30.wbK0r7pvMoZBpOfUQ7rpLZt27nseo3uhVR_lh82sogs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);